<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
</body>

<script>
  /* 
  目标: 进一步掌握async/await的语法和使用
    mdn文档:
      https: //developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/async_function
      https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/await
    1. async 函数
      函数的返回值为promise对象
      promise对象的结果由async函数执行的返回值决定
   
    2. await 表达式
      await右侧的表达式一般为promise对象, 但也可以是其它的值
      如果表达式是promise对象, await返回的是promise成功的值
      如果表达式是其它值, 直接将此值作为await的返回值
    
    3. 注意:
      await必须写在async函数中, 但async函数中可以没有await
      如果await的promise失败了, 就会抛出异常, 需要通过try...catch来捕获处理
    为什么用async和await
      简化promise对象的使用, 不用再通过then指定回调函数取结果数据
      回调地狱的终极解决方案
  */

  // async函数的返回值为promise对象
  async function fn1() {
    // return 1
    // throw 2
    // return Promise.reject(3)
    return Promise.resolve(4)
  }
  // const result = fn1()
  // console.log(result)


  function fn2() {
    // return 2
    // return Promise.resolve(3)
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(4)
      }, 2000)
    })
  }

  // async函数会立即执行结束返回一个pending状态的promise对象
  async function fn3() {
    // await下面的代码会放入then()成功回调中执行的
    const result = await fn2()
    console.log(result)
  }
  // fn3()
  // console.log('fn3()之后')

  // 与async + await 的效果一样
  function fn4() {
    return fn2().then(value => { console.log(value) })
  }
  // fn4()
  // console.log('fn4()之后')


  // 使用try...catch来处理await后的promise失败
  async function fn5() {
     throw 5
  }
  async function fn6() {
    try {
      const result = await fn5()
      console.log('fn6 result=' + result)
    }
    catch (error) {
      console.log('error', error)
    }
  }

  fn6()
</script>

</html>